Feature/adoc 39 file browser
AFTIA/com.aftia.adobe.doc-cloud-services pull request #4
Opened 2022-02-09 15:23 UTC by KyleGJule

2022-02-10 21:16 UTC, GuillaumeCleme requested changes

2022-02-10 21:16 UTC, GuillaumeCleme commented on doc-cloud-services.module/doc-cloud-services.karaf/karaf-doc-cloud/src/main/java/com/aftia/adobe/karaf/doccloud/core/repository/PowerAutomateRepository.java
> +            String json = "{\n" +
Could we build the JSON from a GSON object and serialize it with `json.toString()` in the `StringEntity`?

2022-02-10 22:06 UTC, KyleGJule commented on doc-cloud-services.module/doc-cloud-services.karaf/karaf-doc-cloud/src/main/java/com/aftia/adobe/karaf/doccloud/core/repository/PowerAutomateRepository.java
> +            String json = "{\n" +
Done.

2022-02-11 14:52 UTC, GuillaumeCleme approved these changes

2022-02-11 14:54 UTC, merged